export const BASE_URL =
    "https://www.vinbudin.is/addons/origo/module/ajaxwebservices/search.asmx/DoSearch?skip=0&count=99999";

export const GET_WINES = "GET_WINES";
export const GET_WINE = "GET_WINE";
export const GET_RED_WINES = "GET_RED_WINES";
export const GET_WHITE_WINES = "GET_WHITE_WINES";
export const GET_ROSE_WINES = "GET_ROSE_WINES";
export const GET_SPARKLING_WINES = "GET_SPARKLING_WINES";
export const GET_CHAMPAGNE_WINES = "GET_CHAMPAGNE_WINES";
export const GET_DESSERT_WINES = "GET_DESSERT_WINES";
export const GET_BEERS = "GET_BEERS";
export const GET_SPIRITS = "GET_SPIRITS";
export const GET_CIDERS_AND_SODAS = "GET_CIDERS_AND_SODAS";
export const ITEMS_PER_PAGE = 25;

export const WINE_TYPES = [
    "aromatised",
    "beer",
    "bubbly",
    "ciderfruitandblends",
    "fortified",
    "liqueurshotsandbitter",
    "red",
    "rose",
    "sakeandmead",
    "strong",
    "white",
    "wrapper",
];
export const COUNTRIES = [
    "argentína",
    "armenía",
    "austurríki",
    "bandaríkin",
    "búlgaría",
    "chile",
    "frakkland",
    "georgía",
    "grikkland",
    "króatía",
    "líbanon",
    "makedónía",
    "marokkó",
    "moldóvía",
    "nýjasjáland",
    "portúgal",
    "rúmenía",
    "spánn",
    "suðurafríka",
    "ungverjaland",
    "uruguay",
    "ástralía",
    "ísrael",
    "ítalía",
    "þýskaland",
];
export const REGIONS = [
    "",
    "Abruzzo",
    "Aconcagua",
    "Aconcagua Costa",
    "Acqui",
    "Adelaide",
    "Agulhas Cap",
    "Alba",
    "Alenquer",
    "Alentejano",
    "Alexander Valley",
    "Alicante",
    "Alsace AC",
    "Alsace Grand Cru AC",
    "Anderson Valley",
    "Apalta Valley",
    "Argentína",
    "Arroyo Seco",
    "Asti",
    "Aude",
    "Australia",
    "Banyuls",
    "Barbaresco",
    "Barolo",
    "Barossa Valley",
    "Barsac",
    "Beaujolais",
    "Beaujolais-Villages",
    "Beaune",
    "Beaune Premier Cru",
    "Beeka dalur",
    "Beira Interior",
    "Beneventano",
    "Bergerac",
    "Bianco Dell Empolese ",
    "Blaye Cotes de Bordeaux",
    "Bolgheri",
    "Bordeaux",
    "Bordeaux Superieur",
    "Bourgogne",
    "Brouilly",
    "Burgenland",
    "Cachapoal",
    "Cairanne",
    "Calatayud",
    "Calchaqui Valley",
    "Campania",
    "Canon Fronsac",
    "Cape Town",
    "Carneros",
    "Castelli di Jesi",
    "Castilla",
    "Castilla y Leon",
    "Catalunya",
    "Central Coast",
    "Central Victoria",
    "Chablis",
    "Chablis Grand Cru",
    "Chablis Premier Cru",
    "Chambertin",
    "Chambertin Clos de Beze",
    "Chambolle-Musigny",
    "Chassagne-Montrachet",
    "Chateauneuf-du-Pape",
    "Chianti",
    "Chianti Classico",
    "Chianti Rufina",
    "Chile",
    "Cigales",
    "Cite de Carcassonne",
    "Clare Valley",
    "Coastal Region",
    "Colchagua Valley",
    "Colli Euganei",
    "Colli Orientali del Friuli",
    "Colli della Toscana Centrale",
    "Colline Pescaresi",
    "Columbia Valley",
    "Conca de Barbera",
    "Condrieu",
    "Constantia",
    "Coonawarra",
    "Corbieres",
    "Corbieres Boutenac",
    "Corton-Charlemagne",
    "Costers del Segre",
    "Costieres de Nimes",
    "Cote de Beaune",
    "Cote-Rotie",
    "Coteaux d'Aix-en-Provence",
    "Cotes Catalanes",
    "Cotes de Bourg",
    "Cotes de Gascogne",
    "Cotes de Provence",
    "Cotes de Thau",
    "Cotes du Roussillon",
    "Cotes du Roussillon Villages",
    "Cotes-du-Rhone",
    "Crozes-Hermitage",
    "Cyclades",
    "Dao",
    "Darling",
    "Dealu Mare",
    "Dealurile Olteniei",
    "Delle Venezie",
    "Dolomiti",
    "Dominio de Valdepusa",
    "Douro",
    "Drama",
    "Durbanville",
    "Duriense",
    "East Coast",
    "Eden Valley",
    "Emilia",
    "Emporda",
    "Emporda Costa Brava",
    "Eola-Amity Hills",
    "Etna",
    "Famatina Valley",
    "Fitou",
    "Florina",
    "Franschhoek Valley",
    "Friuli",
    "Fronsac",
    "Garda",
    "Gavi",
    "Gevrey-Chambertin",
    "Gigondas",
    "Gimblett Gravels",
    "Grave del Friuli",
    "Graves",
    "Gualtallary",
    "Haut-Medoc",
    "Hawkes Bay",
    "Hermitage",
    "Imathia",
    "Irpinia",
    "Isonzo del Friuli",
    "Jerez",
    "Judean Hills",
    "Jumilla",
    "Kakheti",
    "Kalifornía",
    "Kamptal",
    "Kindzmarauli",
    "Knights Valley",
    "La Clape",
    "La Mancha",
    "Lalande-de-Pomerol",
    "Lambrusco Emilia",
    "Langhe",
    "Langhorne Creek",
    "Languedoc",
    "Lazio",
    "Leyda",
    "Limarí Valley",
    "Limoux",
    "Lirac",
    "Lisboa",
    "Livermore Valley",
    "Lodi",
    "Loire",
    "Lugana",
    "Lujan de Cuyo",
    "Macon",
    "Macon-Villages",
    "Madeira",
    "Manchuela",
    "Manduria",
    "Manzanilla - Sanlúcar de Barrameda",
    "Marca Trevigiana",
    "Maremma Toscana",
    "Margaux",
    "Marlborough",
    "Marsala",
    "Maule Valley",
    "McLaren Vale",
    "Medoc",
    "Mendoza",
    "Meursault",
    "Meursault Premier Cru",
    "Minervois La Liviniere",
    "Montagne-Saint-Emilion",
    "Montagny Premier Cru",
    "Montalcino",
    "Montecucco",
    "Montepulciano",
    "Monterey County",
    "Montrachet Grand Cru",
    "Morelino di Scansano",
    "Morgon",
    "Mosel",
    "Moulin-a-Vent",
    "Mount Harlan",
    "Mukuzani",
    "Murray Darling",
    "Nahe",
    "Naoussa",
    "Napa Valley",
    "Navarra",
    "Neusiedlersee",
    "Neusiedlersee Hugelland",
    "Niederosterreich",
    "North Coast",
    "Nuits-Saint-Georges Premier Cru",
    "Oakville District",
    "Oregon",
    "Paarl",
    "Paso Robles",
    "Pauillac",
    "Pays d'Oc",
    "Penedes",
    "Peninsula de Setubal",
    "Pessac-Leognan",
    "Petit Chablis",
    "Pfalz",
    "Pic Saint Loup",
    "Piceno",
    "Piemonte",
    "Pineau des Charentes",
    "Pomerol",
    "Pommard Premier Cru",
    "Pouilly-Fuissé",
    "Pouilly-Fumé",
    "Priorat",
    "Provinca di Pavia",
    "Puente Alto",
    "Puglia",
    "Rapel Valley",
    "Rhein",
    "Rheingau",
    "Rheinhessen",
    "Rias Baixas",
    "Ribeiro",
    "Ribera del Duero",
    "Ribera del Queiles",
    "Rioja",
    "Riverland / King Valley",
    "Robertson",
    "Roero",
    "Rose Valley",
    "Rubicone",
    "Rueda",
    "Russian River Valley",
    "Rutherford",
    "Saint-Aubin Premier Cru",
    "Saint-Emilion",
    "Saint-Emilion Grand Cru",
    "Saint-Estephe",
    "Saint-Joseph",
    "Saint-Julien",
    "Salento",
    "Salta",
    "San Antonio",
    "San Gimignano",
    "San Juan",
    "Sancerre",
    "Sannio",
    "Santa Barbara",
    "Santa Cruz Mountains",
    "Santa Maria Valley",
    "Santenay Premier Cru",
    "Santorini",
    "Sardegna",
    "Sauternes",
    "Savigny-Les-Beaune",
    "Savigny-Les-Beaune 1er Cru",
    "Sicilia",
    "Simonsberg Paarl",
    "Soave Classico",
    "Somontano",
    "Sonoma Coast",
    "Sonoma County",
    "South Australia",
    "South Eastern Australia",
    "Spánn",
    "Stellenbosch",
    "Sudtiroler-Alto Adige",
    "Swartland",
    "Taurasi",
    "Tejo",
    "Terra Alta",
    "Terre Siciliane",
    "Terre di Chieti",
    "Terres du Midi",
    "Thermenregion",
    "Thracian Valley Region",
    "Tikves",
    "Tokaj Hegyalia",
    "Toro",
    "Toscana",
    "Trentino",
    "Trevenezie",
    "Tufo",
    "Tupungato",
    "Umbria",
    "Utiel-Requena",
    "Val d'Arno di Sopra",
    "Val de Loire",
    "Valdadige",
    "Valdeorras",
    "Valdiciana Toscana",
    "Valencia",
    "Vallagarina",
    "Valle Central",
    "Valle de Casablanca",
    "Valle de Curico",
    "Valle de Uco",
    "Valle del Maipo",
    "Valpolicella",
    "Valpolicella Classico",
    "Var",
    "Veneto",
    "Venezia",
    "Venezia Giulia",
    "Verona",
    "Veronese",
    "Victoria",
    "Villany",
    "Vin de France",
    "Vinho Verde",
    "Vino da Italia",
    "Vosne-Romanée",
    "Vouvray",
    "Wachau",
    "Washington",
    "Western Cape",
    "Willamette Valley",
    "Yecla",
];
export const FOOD_PAIRINGS = [
    "Beef",
    "Pork",
    "Lamb",
    "Game (deer, venison)",
    "Spicy food",
    "Poultry",
    "Cured meat",
    "Veal",
    "Exotic food",
    "Fish",
    "Vegetarian",
    "Goat cheese",
    "Blue cheese",
    "Hard cheese",
    "Pasta",
    "Salad",
    "Shellfish",
    "Crab",
    "Lobster",
    "Salmon",
    "Tuna",
    "Sushi",
    "Curry",
    "Thai",
    "Indian",
    "Chinese",
    "Japanese",
    "Mexican",
    "Spanish",
    "Italian",
    "BBQ",
    "Chocolate",
];
